name: Stale Issues & PRs
on:
  schedule:
    - cron: "0 14 * * *"
    - cron: "0/1 * * * *" # JUST FOR TESTING

jobs:
  echo-a-string:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Triggered"