name: Working Dirs & Shells
on: [push]
defaults:
  run:
    working-directory: /home
jobs:
  display-wd-info:
    runs-on: ubuntu-latest
    steps:
      - name: Display workging Directory & List Files
        run: |
          pwd
          ls -lisa
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
      - name: Change Working Dir
        working-directory: /home/runner
        run: pwd
  display-wd-info-windows:
    runs-on: windows-latest
    steps:
      - name: Display workging Directory & List Files
        run: |
          Get-Location
          dir
          echo $env:GITHUB_SHA
          echo $env:GITHUB_REPOSITORY
          echo $env:GITHUB_WORKSPACE